version: '3'
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    hostname: post-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post-db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - post-db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  post-db:
    driver: local
